name: Run script for the twitter bot

on:
  schedule:
    - cron: '0 10 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install package and run the script
      run: npm i && node index.js